# 起手式
* 載入基本套件
* 讀圖 >> 等待按鍵 >> 釋放記憶體
* 存圖

In [1]:
import numpy as np
import cv2
img = cv2.imread('Lenna.jpg')
cv2.imshow('window', img)
cv2.waitKey()

cv2.destroyWindow('window') #釋放指定視窗
#cv2.destroyAllWindows() #釋放所有視窗

In [2]:
new_img = cv2.imwrite('Lenna_write.jpg', img)

二值影像：只有黑白兩色，在電腦中以0表示黑色，以1表示白色。
灰階影像：通常會有２５６的灰階層級，以0～255表示。
彩色影像：有R、G、B三通道，每個通道值的範圍在０～２５５間。在OpenCV中，通道的順序是B、G、R。

In [3]:
image = np.zeros((300, 300, 3), dtype = np.uint8)
image[:,0:100,0] = 255
image[:, 100:200, 1] = 255
image[:, 200:300, 2] = 255
print("image=\n",image)
cv2.imshow('image', image)
cv2.waitKey()
cv2.destroyAllWindows()

image=
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]



item() 存取像素值
itemset() 修該象素質

In [4]:
import numpy as np
img = np.random.randint(10, 99, size=[5,5], dtype = np.uint8)
print("img=\n", img)
print("讀取像素點 img.item(3,2)=", img.item(3,2))
img.itemset((3,2),255)
print("修改後img=\n", img)
print("修該後像素點 img.item(3,2)=", img.item(3,2))

img=
 [[47 32 88 11 15]
 [49 25 87 35 70]
 [23 53 25 98 49]
 [22 26 53 92 12]
 [98 93 36 16 42]]
讀取像素點 img.item(3,2)= 53
修改後img=
 [[ 47  32  88  11  15]
 [ 49  25  87  35  70]
 [ 23  53  25  98  49]
 [ 22  26 255  92  12]
 [ 98  93  36  16  42]]
修該後像素點 img.item(3,2)= 255


In [5]:
img = cv2.imread('Lenna.jpg')
cv2.imshow('before', img)
print('存取img.item(0,0,0)=', img.item(0,0,0))
print('存取img.item(0,0,1)=', img.item(0,0,1))
print('存取img.item(0,0,2)=', img.item(0,0,2))

for i in range(0, 50):
    for j in range(0, 100):
        for k in range(0, 3):
            img.itemset((i,j,k), 255)
cv2.imshow('after', img)
print('修改後img.item(0,0,0)=', img.item(0,0,0))
print('修改後img.item(0,0,1)=', img.item(0,0,1))
print('修改後img.item(0,0,2)=', img.item(0,0,2))
            
cv2.waitKey()
cv2.destroyAllWindows()

存取img.item(0,0,0)= 125
存取img.item(0,0,1)= 137
存取img.item(0,0,2)= 225
修改後img.item(0,0,0)= 255
修改後img.item(0,0,1)= 255
修改後img.item(0,0,2)= 255


In [6]:
#通道拆分
import numpy as np
import cv2
img = cv2.imread('Lenna.jpg')
cv2.imshow('lena',img)

b = img[:,:,0]
g = img[:,:,1]
r = img[:,:,2]

cv2.imshow('b',b)
cv2.imshow('g',g)
cv2.imshow('r',r)

img[:,:,0]=0
cv2.imshow('lenab0',img)
img[:,:,1]=0
cv2.imshow('lenab0g0',img)

cv2.waitKey()
cv2.destroyAllWindows()


#更簡潔的通道拆分函示
b, g, r = cv2.split(img)

In [7]:
#通道合併
import numpy as np
import cv2
img = cv2.imread('Lenna.jpg')
cv2.imshow('lena',img)
b,g,r = cv2.split(img)
bgr = cv2.merge([b,g,r])
rgb = cv2.merge([r,g,b])

cv2.imshow('bgr',bgr)
cv2.imshow('rgb',rgb)

cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
#檢視影像屬性
print(img.shape)
print(img.size)
print(img.dtype)

(316, 316, 3)
299568
uint8


# 影像運算

In [9]:
#情況一 "+" 若 a+b > 255，則會取mod

#情況二 cv2.add(a,b)  
# 若a+b的值大於255，計算結果則為255

import numpy as np
import cv2
a = cv2.imread('Lenna.jpg')
cv2.imshow('original',a)

b = a
result1 = a + b
result2 = cv2.add(a, b)
cv2.imshow('a+b',result1)
cv2.imshow('cv2.add(a, b)',result2)

cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
#位元運算 birwise_and

import numpy as np
import cv2
a = cv2.imread('Lenna.jpg')
b = np.zeros(a.shape, dtype=np.uint8)
b[50:150, 50:150] = 255
b[50:160, 50:60] = 255
c = cv2.bitwise_and(a,b)
print('a.shpae=', a.shape)
print('b.shape=', b.shape)
cv2.imshow('original',a)
cv2.imshow('mask',b)
cv2.imshow('result',c)

cv2.waitKey()
cv2.destroyAllWindows()

a.shpae= (316, 316, 3)
b.shape= (316, 316, 3)


In [11]:
#位元運算 birwise_or

import numpy as np
import cv2
a = cv2.imread('Lenna.jpg')
b = np.zeros(a.shape, dtype=np.uint8)
b[50:150, 50:150] = 255 #任何數值與255運算會得到數值本身，因此透過此設定保留我們要的區域。
b[50:160, 50:60] = 255
c = cv2.bitwise_or(a,b)
print('a.shpae=', a.shape)
print('b.shape=', b.shape)
cv2.imshow('original',a)
cv2.imshow('mask',b)
cv2.imshow('result',c)

cv2.waitKey()
cv2.destroyAllWindows()

a.shpae= (316, 316, 3)
b.shape= (316, 316, 3)


In [12]:
#位元運算 birwise_not

import numpy as np
import cv2
a = cv2.imread('Lenna.jpg')
c = cv2.bitwise_not(a)
print('a.shpae=', a.shape)
cv2.imshow('original',a)
cv2.imshow('result',c)

cv2.waitKey()
cv2.destroyAllWindows()

a.shpae= (316, 316, 3)


In [13]:
#位元運算 birwise_xor

import numpy as np
import cv2
a = cv2.imread('Lenna.jpg')
b = np.zeros(a.shape, dtype=np.uint8)
b[50:150, 50:150] = 255
b[50:160, 50:60] = 255
c = cv2.bitwise_xor(a, b)
print('a.shpae=', a.shape)
print('b.shape=', b.shape)
cv2.imshow('original',a)
cv2.imshow('mask',b)
cv2.imshow('result',c)
 
cv2.waitKey()
cv2.destroyAllWindows()

a.shpae= (316, 316, 3)
b.shape= (316, 316, 3)


In [14]:
#位元平面分解

import numpy as np
import cv2

img = cv2.imread('Lenna.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('Lenna', img)

# Step1.獲取影像資訊
r, c = img.shape #顯示影像列寬*行高

# Step2.建立分析矩陣
x = np.zeros((r, c, 8), dtype=np.uint8) #建立一個位元分析矩陣，大小為 r*c*8。8表示分析灰階影像的第8個位元平面。
for i in range(8):  #設定用於分析各個位元平面的分析矩陣之值
    x[:,:,i] = 2 ** i
    #print(x)

#Step3. 分析位元平面
bitplane = np.zeros((r, c, 8), dtype=np.uint8) 
for i in range(8): #進行各位元平面分析
    bitplane[:,:,i] = cv2.bitwise_and(img, x[:,:,i])    
    mask = bitplane[:,:,i]>0 #將位元平面中大於0的值設為True，小於0的值設為False
# Step4.設定值處理    
    bitplane[mask] = 255 #讓二值化影像可以清楚黑白顯示
    cv2.imshow(str(i), bitplane[:,:,i])  #顯示各位元影像
 
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
#影像加密與解密
import numpy as np
import cv2

img = cv2.imread('Lenna.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('Lenna', img)
r, c = img.shape #顯示影像列寬*行高

key = np.random.randint(0, 256, size=(r, c), dtype = np.uint8)
encryption = cv2.bitwise_xor(img, key)
decryption = cv2.bitwise_xor(encryption, key)

cv2.imshow('key', key)
cv2.imshow('encryption', encryption)
cv2.imshow('decryption', decryption)

cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
#針對ROI區域加密
import numpy as np
import cv2

img = cv2.imread('Lenna.jpg', cv2.IMREAD_GRAYSCALE) #以灰階的方式顯示圖片
r, c = img.shape #顯示影像列寬*行高

#建立遮罩
mask = np.zeros(img.shape, dtype=np.uint8) #建立一個和原圖大小相同的遮罩
mask[150:180, 150:180] = 1 #在遮罩範圍中，設定ROI為1，其餘區域為0

#建立加密與解密用之金鑰
key = np.random.randint(0, 256, size=(r, c), dtype = np.uint8) #建立一個和原圖大小相同的金鑰，每個像素值介於0~256
 
#各種情況的加密
encrypt_img = cv2.bitwise_xor(img, key) #對原始影像加密
encrypt_ROI = cv2.bitwise_and(encrypt_img, mask*255) #取加密後的ROI

bg = cv2.bitwise_or(img, mask*255) #取mask外的背景。任何數值與255運算會得到數值本身，因此透過此設定保留我們要的區域。
#bg = cv2.bitwise_and(img, (1-mask)*255) #另一種取背景的方法

encrypt_ROI_img = encrypt_ROI + bg #將加密的區域與背景相加

print('img.shpae=', img.shape) #顯示原圖列寬和行高
print('mask.shape=', mask.shape) #顯示遮罩列寬和行高
cv2.imshow('original',img) #顯示原圖
cv2.imshow('mask',mask) #顯示遮罩
cv2.imshow('encrypt_img', encrypt_img) #顯示加密後的原圖
cv2.imshow('encrypt_ROI', encrypt_ROI) #顯示加密後的原圖ROI
cv2.imshow('bg', bg) #顯示ROI外的圖
cv2.imshow('encrypt_ROI_img', encrypt_ROI_img) #顯示整張圖片與加密的ROI區域

cv2.waitKey()
cv2.destroyAllWindows()

img.shpae= (316, 316)
mask.shape= (316, 316)
