In [1]:
# BGR to RGB
import numpy as np
import cv2

img = cv2.imread('Lenna.jpg')
rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

cv2.imshow('BGR', img)
cv2.imshow('RGB', rgb_img)

cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
#篩選指定像素範圍
import numpy as np
import cv2

img = cv2.imread('Lenna.jpg', cv2.IMREAD_GRAYSCALE)
filter_img = cv2.inRange(img, 0, 100)

cv2.imshow('original', img)
cv2.imshow('filter_img', filter_img)

print(filter_img)

cv2.waitKey()
cv2.destroyAllWindows()

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255   0   0]
 [255 255 255 ...   0   0   0]]


In [3]:
#擷取指定顏色
import numpy as np
import cv2

img = cv2.imread('Lenna.jpg')
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(img_hsv)
minHue = 5
maxHue = 170
hus_mask = cv2.inRange(h, minHue, maxHue)

minSat = 25
maxSat = 166
sat_mask = cv2.inRange(s, minSat, maxSat)

mask = hus_mask & sat_mask

ROI_img = cv2.bitwise_and(img, img, mask=mask)

cv2.imshow('original', img)
cv2.imshow("ROI_img",ROI_img)

cv2.waitKey()
cv2.destroyAllWindows()

In [20]:
#藝術效果
import numpy as np
import cv2

img = cv2.imread('Lenna.jpg')
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(img_hsv)
v[:,:]=255
new_hsv = cv2.merge([h,s,v])
art_img = cv2.cvtColor(new_hsv, cv2.COLOR_HSV2BGR)

cv2.imshow('original', img)
cv2.imshow('art_img', art_img)

cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
#對影像的alpha通道進行處理
#alpha通道表示透明度，值從0~255。
import numpy as np
import cv2

img = cv2.imread('Lenna.jpg')
bgra_img = cv2.cvtColor(img, cv2.COLOR_BGR2BGRA)
b, g, r, a = cv2.split(bgra_img)
a[:,:] = 125
bgra_img_125 = cv2.merge([b, g, r, a])

a[:,:] = 0
bgra_img_0 = cv2.merge([b, g, r, a])

cv2.imshow('original', img)
cv2.imshow('bgra_img', bgra_img)
cv2.imshow('bgra_img_125', bgra_img_125)
cv2.imshow('bgra_img_0', bgra_img_0)

cv2.imwrite('bgra_img.png', bgra_img)
cv2.imwrite('bgra_img_125.png', bgra_img_125)
cv2.imwrite('bgra_img_0.png', bgra_img_0)

cv2.waitKey()
cv2.destroyAllWindows()